// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCusmHMZ_ieZ_LIaPTg4DWht-W9gIr8ysU',
    appId: '1:146616149514:web:19ae6a1e026153836421f3',
    messagingSenderId: '146616149514',
    projectId: 'top-docteur',
    authDomain: 'top-docteur.firebaseapp.com',
    storageBucket: 'top-docteur.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF8wvJEC_1xeVwDiwGeW0cHUQv7nYNO6k',
    appId: '1:146616149514:android:8876f1d9d8219e326421f3',
    messagingSenderId: '146616149514',
    projectId: 'top-docteur',
    storageBucket: 'top-docteur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnSAW7pS7g9C3yhDv2rnSdKBZ5hV1EtyQ',
    appId: '1:146616149514:ios:cb4e1e0e24b6e5ac6421f3',
    messagingSenderId: '146616149514',
    projectId: 'top-docteur',
    storageBucket: 'top-docteur.appspot.com',
    iosBundleId: 'com.example.topDocteur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnSAW7pS7g9C3yhDv2rnSdKBZ5hV1EtyQ',
    appId: '1:146616149514:ios:342ee16827865bbd6421f3',
    messagingSenderId: '146616149514',
    projectId: 'top-docteur',
    storageBucket: 'top-docteur.appspot.com',
    iosBundleId: 'com.example.topDocteur.RunnerTests',
  );
}
